#! /bin/sh
### BEGIN INIT INFO
# Provides: ghost2
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: GHost/2
# Description: This file starts and stops the GHost/2 server
# Written by: Dean Warren theshadowlandsbbs.ssccbogart.info
### END INIT INFO

# Set Directory and PID file
GHOST_DIR=/ghost
file=/var/run/ghost/start_sh.pid

case "$1" in
 start)
   # If case start then call start.sh in /GHost
   $GHOST_DIR/start.sh 
   ;;
 stop)
   # If case stop call stop.sh in /GHost
   $GHOST_DIR/stop.sh 
   sleep 10
   ;;
 restart)
   # If  case restart then stop and start from /GHost
   $GHOST_DIR/stop.sh 
   sleep 20
   $GHOST_DIR/start.sh 
   ;;
 status)
    # If case status check to see if PID exist(more error checking to do here in the future)
    if [ -e $file ]; 
    then echo "GHost/2 process running."
    else echo "No pid found. Process might be stopped."
    fi
   ;;
 *)
   echo "Usage: ghost2 {start|stop|restart|status}" >&2
   exit 3
   ;;
esac
