@ECHO OFF

ECHO DELETING UNNECESSARY FILES
DEL MONO.POSIX.DLL
DEL PTY-SHARP.DLL
DEL *.PDB
DEL *.XML
DEL *.CONFIG

ECHO.
ECHO HIT A KEY TO PACKAGE DOOR-FREE VERSION
PAUSE > NUL
DEL ..\GHost-NODOORS.ZIP
"C:\PROGRAM FILES\7-ZIP\7Z.EXE" a -mx5 -r -tzip -x!_RELEASE.CMD -x!*.VSHOST.EXE ..\GHost2_v_.zip *.*

:END

ECHO.
ECHO HIT A KEY TO QUIT
PAUSE > NUL